### PR TITLE
Move trace_link.py to mlcommons/chakra

### PR DESCRIPTION
**Pull request by TaekyungHeo**
Move trace_link.py to [mlcommons/chakra](https://github.com/mlcommons/chakra) based on the discussion between Meta and NVIDIA.

### CODE REVIEW

**Review by briancoutinho — APPROVED** [review]
lgtm :) we will do the move to chakra :)

**Comment by TaekyungHeo** [comment]
@briancoutinho , What can I do to fix these lint errors?

**Comment by TaekyungHeo** [comment]
@briancoutinho, I rebased it to the latest main branch to unblock it.

**Comment by briancoutinho** [comment]
@TaekyungHeo I had to delete the Meta internal TARGET, just did it, i'll handle landing this (Y)

**Pull request closed without merging**
